/*
Track & Trace Events

Retrieve Track & Trace Events based on DCSA Interface standard v.2.2  This service provides shippers and consignees visibility to Shipment, Equipment and Transport events for shipments booked with A.P. Moller-Maersk A/S using standards set by the Digital Container Shipping Association.\\ <https://dcsa.org/>

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package maersk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiValidationError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiValidationError{}

// ApiValidationError struct for ApiValidationError
type ApiValidationError struct {
	// The field that has failed validation.
	Field string `json:"field"`
	// The value that has failed validation.
	RejectedValue string `json:"rejectedValue"`
	// The reason and advice for failed validation.
	Message string `json:"message"`
}

type _ApiValidationError ApiValidationError

// NewApiValidationError instantiates a new ApiValidationError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiValidationError(field string, rejectedValue string, message string) *ApiValidationError {
	this := ApiValidationError{}
	this.Field = field
	this.RejectedValue = rejectedValue
	this.Message = message
	return &this
}

// NewApiValidationErrorWithDefaults instantiates a new ApiValidationError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiValidationErrorWithDefaults() *ApiValidationError {
	this := ApiValidationError{}
	return &this
}

// GetField returns the Field field value
func (o *ApiValidationError) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *ApiValidationError) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *ApiValidationError) SetField(v string) {
	o.Field = v
}

// GetRejectedValue returns the RejectedValue field value
func (o *ApiValidationError) GetRejectedValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RejectedValue
}

// GetRejectedValueOk returns a tuple with the RejectedValue field value
// and a boolean to check if the value has been set.
func (o *ApiValidationError) GetRejectedValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RejectedValue, true
}

// SetRejectedValue sets field value
func (o *ApiValidationError) SetRejectedValue(v string) {
	o.RejectedValue = v
}

// GetMessage returns the Message field value
func (o *ApiValidationError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiValidationError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiValidationError) SetMessage(v string) {
	o.Message = v
}

func (o ApiValidationError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiValidationError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["rejectedValue"] = o.RejectedValue
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ApiValidationError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"rejectedValue",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiValidationError := _ApiValidationError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiValidationError)

	if err != nil {
		return err
	}

	*o = ApiValidationError(varApiValidationError)

	return err
}

type NullableApiValidationError struct {
	value *ApiValidationError
	isSet bool
}

func (v NullableApiValidationError) Get() *ApiValidationError {
	return v.value
}

func (v *NullableApiValidationError) Set(val *ApiValidationError) {
	v.value = val
	v.isSet = true
}

func (v NullableApiValidationError) IsSet() bool {
	return v.isSet
}

func (v *NullableApiValidationError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiValidationError(val *ApiValidationError) *NullableApiValidationError {
	return &NullableApiValidationError{value: val, isSet: true}
}

func (v NullableApiValidationError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiValidationError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
